package categorias;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author darkzide
 */
public class RevCategoria extends javax.swing.JFrame {

    /**
     * Creates new form RevCategoria
     */
    public RevCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        marca.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {

            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    Thread hilo = new Thread(new Runnable() {

                        @Override
                        public void run() {
                            String system = System.getProperty("os.name");
                            if (system.equals("Linux")) {
                                loading.setIcon(new ImageIcon("/home/darkzide/NetBeansProjects/ReveladorCategoria/loading.gif"));
                            } else if (system.equals("Windows")) {
                                loading.setIcon(new ImageIcon("C:\\dist\\loading.gif"));
                            }
                            buscar();
                        }

                    });
                    hilo.start();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        marca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaCategorias = new javax.swing.JTextArea();
        loading = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exacta = new javax.swing.JRadioButton();
        aproximada = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Categoria");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel2.setText("Marca:");

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel3.setText("Categoria:");

        areaCategorias.setEditable(false);
        areaCategorias.setColumns(20);
        areaCategorias.setLineWrap(true);
        areaCategorias.setRows(5);
        jScrollPane1.setViewportView(areaCategorias);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel4.setText("Tipo de busqueda:");

        buttonGroup1.add(exacta);
        exacta.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        exacta.setSelected(true);
        exacta.setText("Exacta");

        buttonGroup1.add(aproximada);
        aproximada.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        aproximada.setText("Aproximada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(47, 47, 47)
                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exacta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aproximada)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(exacta)
                    .addComponent(aproximada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loading)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Thread hilo = new Thread(new Runnable() {

            @Override
            public void run() {
                String system = System.getProperty("os.name");
                if (system.equals("Linux")) {
                    loading.setIcon(new ImageIcon("/home/darkzide/NetBeansProjects/ReveladorCategoria/loading.gif"));
                } else if (system.equals("Windows")) {
                    loading.setIcon(new ImageIcon("C:\\dist\\loading.gif"));
                }
                buscar();
            }

        });
        hilo.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void buscar() {
        areaCategorias.setText("");

        Connection con = Conexion.getConnection();
        PreparedStatement pst = null;
        ResultSet result = null;
        String query1 = "SELECT\n"
                + "	Categoria\n"
                + "FROM\n"
                + "	ncategorias\n"
                + "WHERE\n"
                + "	id IN (\n"
                + "		SELECT\n"
                + "			id_categoria\n"
                + "		FROM\n"
                + "			asigmarcacategoria\n"
                + "		WHERE\n"
                + "			id_marca IN (\n"
                + "				SELECT\n"
                + "					id\n"
                + "				FROM\n"
                + "					nmarcas\n"
                + "				WHERE\n"
                + "					marca LIKE '%" + marca.getText() + "%'\n"
                + "			)\n"
                + "	)";

        String query2 = "SELECT\n"
                + "	Categoria\n"
                + "FROM\n"
                + "	ncategorias\n"
                + "WHERE\n"
                + "	id IN (\n"
                + "		SELECT\n"
                + "			id_categoria\n"
                + "		FROM\n"
                + "			asigmarcacategoria\n"
                + "		WHERE\n"
                + "			id_marca IN (\n"
                + "				SELECT\n"
                + "					id\n"
                + "				FROM\n"
                + "					nmarcas\n"
                + "				WHERE\n"
                + "					marca = '" + marca.getText() + "'\n"
                + "			)\n"
                + "	)";

        try {
            if (exacta.isSelected()) {
                pst = con.prepareStatement(query2);
            } else if (aproximada.isSelected()) {
                pst = con.prepareStatement(query1);
            }

            result = pst.executeQuery();
            ArrayList<String> list = new ArrayList<>();
            int cont = 0;
            while (result.next()) {
                cont++;
                list.add(result.getString("Categoria"));

            }
            if (cont >= 1) {
                for (String list1 : list) {
                    areaCategorias.append(list1 + "\n");
                }
            } else if (cont < 1) {
                areaCategorias.setText("No hay categoria relacionada");
            }
            marca.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al hacer la consulta: " + ex);
        } finally {
            try {
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexion");
            }
        }
        loading.setIcon(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            JFrame.setDefaultLookAndFeelDecorated(true);

            JDialog.setDefaultLookAndFeelDecorated(true);

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (Exception e) {

            e.printStackTrace();

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevCategoria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aproximada;
    private javax.swing.JTextArea areaCategorias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton exacta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loading;
    private javax.swing.JTextField marca;
    // End of variables declaration//GEN-END:variables
}
